FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD com.org.jar /opt/com.org/
EXPOSE 8080
WORKDIR /opt/com.org/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "com.org.jar"]
